export const SCREEN = {
  GSD_ANALYSIS: 'GSD.ANALYSIS',
  SEWING_PROCESS: 'SEWING.PROCESS',
  OPERATION_CLUSTER: 'OPERATION_CLUSTER.MAIN',

  SYSTEM_EMPLOYEES: 'SYSTEM.EMPLOYEES',
  SYSTEM_USERS: 'SYSTEM.USERS',
  SYSTEM_ROLES: 'SYSTEM.ROLES',
  SYSTEM_SCREENS: 'SYSTEM.SCREENS',
  SYSTEM_WORKFLOW: 'SYSTEM.WORKFLOW',
  SYSTEM_AUDIT: 'SYSTEM.AUDIT',
} as const;

export const ACTION = {
  VIEW: 'VIEW',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  EXPORT: 'EXPORT',
  APPROVE: 'APPROVE',
  REVIEW: 'REVIEW',
  SUBMIT: 'SUBMIT',
  REJECT: 'REJECT',
  RETURN: 'RETURN',
  MONITOR: 'MONITOR',
  MANAGE: 'MANAGE',
  CALCULATE: 'CALCULATE',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',

  LOCK: 'LOCK',
  RESET_PASSWORD: 'RESET_PASSWORD',
} as const;